---
- name: add azure credential
  awx.awx.credential:
    name: azure_credential
    description: Azure Service Principle
    organization: "Default"
    state: present
    credential_type: Microsoft Azure Resource Manager
    inputs:
      subscription: "{{ my_subscription }}"
      tenant: "{{ my_tenant }}"
      client: "{{ my_client }}"
      secret: "{{ my_secret }}"
    controller_username: "{{ my_controller_username }}"
    controller_password: "{{ my_controller_password }}"
    controller_host: "{{ my_controller_host }}"
    validate_certs: false
