---
- name: grab linux facts
  hosts: "{{ HOSTS | default('web') }}"
  gather_facts: true

- name: build developer report
  hosts: "{{ HOSTS[0] | default('node1') }}"
  gather_facts: false

  vars:
    file_path: /var/www/html/report/index.html

  tasks:
    - name: use developer report
      include_role:
        name: "../../roles/developer_report"
